resolver: lts-11.9
flags: {}
packages:
- '.'
docker:
  enable: true
  repo: us.gcr.io/forward-lead-160122/stack-build:lts-11.9
extra-deps:
  - git: git@github.com:rumuki/gogol.git
    commit: 344c9f781560e1ed8395b17e370ba1b085f2edc2
    subdirs:
      - core
      - gogol
      - gogol-storage
  - HDBC-postgresql-2.3.2.5
  - dbmigrations-2.0.0
  - yaml-light-0.1.4
  - HsSyck-0.53
