flags: {}
packages:
- '.'
docker:
  enable: true
  repo: nathankot/rumuki-stack-build:lts-8.9
extra-deps:
- HDBC-postgresql-2.3.2.4
- HsSyck-0.53
- aws-0.16
- data-easy-0.7.0
- dbmigrations-2.0.0
- gogol-0.3.0
- gogol-core-0.3.0
- gogol-storage-0.3.0
- load-env-0.1.1
- yaml-light-0.1.4
resolver: lts-8.9
