InvalidEmailAddress: Invalid email address
DeviceNotFound: Device not found
DeviceTokenTooShort min@Int: Device token is too short (at least >= #{show min})
Unauthorized: Unauthorized
PlaybackRecipientNotFound: Playback recipient not found
PlaybackGrantNotFound: This playback grant no longer exists
NewPlaybackGrantReceived: New playback grant received
ScreenCaptureDetected: Screen capture detected for one of your recordings
