InvalidEmailAddress: Invalid email address
DeviceNotFound: Device not found
DeviceTokenTooShort min@Int: Device token is too short (at least >= #{show min})
Unauthorized: Unauthorized
PlaybackRecipientNotFound: Playback recipient not found
PlaybackGrantNotFound: This playback grant no longer exists
PerpetualGrantNotFound: This perpetual grant no longer exists
NewPlaybackGrantReceived: New playback grant received
NewPerpetualGrantReceived: A recording has been made available for playback
NewRemoteRecordingReceived: New recording received
ScreenCaptureDetected: Screen capture detected for one of your recordings
TransferForRecordingAlreadyExists: A transfer for this recording already exists
